config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'breweries#index'
  get 'kaikki_bisset', to: 'beers#index'
  resources :ratings, only: [:index, :new, :create, :destroy]
  get 'signup', to: 'users#new'
  resource :session, only: [:new, :create, :destroy]
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  resources :memberships, only: [:index,:new, :create, :destroy]
  resources :places, only: [:index, :show]
  get 'places', to: 'places#index'
  post 'places', to:'places#search'
  get 'styles', to: 'styles#index'
  resources :styles, only: [:index, :show, :create, :destroy, :edit]
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :users do
    post 'toggle_activity', on: :member
  end
  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'
  get 'auth/:provider/callback', to: 'sessions#create_oauth'
  resources :memberships do
    post 'toggle_confirmed', on: :member
  end
end

app/models/beer_club.rb
class BeerClub < ApplicationRecord
  has_many :memberships
  has_many :users, through: :memberships

  def user_not_member?(user)
    is = true
    users.each do |u|
      if user == u
        is = false
      end
    end
    is
  end
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :set_beer_club, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_admin, only: [:destroy]

  # GET /beer_clubs
  # GET /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all

    order = params[:order] || 'name'

    @beer_clubs = case order
                  when 'name' then @beer_clubs.sort_by(&:name)
                  when 'founded' then @beer_clubs.sort_by(&:founded)
                  when 'city' then @beer_clubs.sort_by(&:city)
                  end
  end

  # GET /beer_clubs/1
  # GET /beer_clubs/1.json
  def show
    @unconfirmed = @beer_club.memberships.where(confirmed: false).all
    if current_user && !@beer_club.user_not_member?(current_user)
      @membership = Membership.find_by user_id: current_user.id
    else
      @membership = Membership.new
      @membership.beer_club = @beer_club
    end
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs
  # POST /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)

    respond_to do |format|
      if @beer_club.save
        @beer_club.users << current_user
        @beer_club.memberships.find_by_user_id(current_user.id).update_attribute(:confirmed, true)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully created.' }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1
  # PATCH/PUT /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1
  # DELETE /beer_clubs/1.json
  def destroy
    @beer_club.destroy
    respond_to do |format|
      format.html { redirect_to beer_clubs_url, notice: 'Beer club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_beer_club
    @beer_club = BeerClub.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def beer_club_params
    params.require(:beer_club).permit(:name, :founded, :city)
  end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_form.html.erb
<%= form_for(@beer_club) do |f| %>
  <% if @beer_club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
      <% @beer_club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:"form-control", placeholder:"Enter name" %>
  </div>
  <div class="field">
    <%= f.label :founded %><br>
    <%= f.number_field :founded,class:"form-control", placeholder:"Enter the year when founded" %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city, class:"form-control", placeholder:"Enter city" %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-primary" %>
  </div>
</div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing Beer Club</h1>

<%= render 'form', beer_club: @beer_club %>

<%= link_to 'Show', @beer_club %> |
<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/index.html.erb
<h1>Beer Clubs</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th> <%= link_to 'Name', beer_clubs_path(order:"name") %> </th>
      <th> <%= link_to 'Founded', beer_clubs_path(order:"founded") %> </th>
      <th> <%= link_to 'City', beer_clubs_path(order:"city") %> </th>
    </tr>
  </thead>

  <tbody>
    <% @beer_clubs.each do |club| %>
      <tr>
        <td><%= link_to club.name, club %></td>
        <td><%= club.founded %></td>
        <td><%= club.city %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to('New Beer Club', new_beer_club_path, class:'btn btn-primary') if current_user %>

app/views/beer_clubs/new.html.erb
<h1>New Beer Club</h1>

<%= render 'form', beer_club: @beer_club %>

<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/show.html.erb
<h1>
  <%= @beer_club.name %> <%= @beer_club.city %> 
</h1>

<p>
  Founded 
  <%= @beer_club.founded %>
</p>

<h2>Members</h2>
<ul>
 <% @beer_club.users.each do |member| %>
  <% if @beer_club.memberships.find_by_user_id(member.id).confirmed == true %>
    <%= link_to member do %>
   <li> <%= member.username %> </li>
    <% end %>
    <% end%>
 <% end %>
</ul>

<% if current_user && !@beer_club.user_not_member?(current_user) && @beer_club.memberships.find_by_user_id(current_user.id).confirmed == true %>
<h2>Outstanding applications <h2>
<% @unconfirmed.each do |m| %>
   <p> <%= User.find_by_id(m.user_id).username %>
    <%= link_to "confirm", toggle_confirmed_membership_path(m.id), method: :post, class: "btn btn-primary" %>
    </p>
<%end%>


<% end %>

<% if current_user && @beer_club.user_not_member?(current_user) %>

  <%= form_for(@membership) do |f| %>
    <%= f.hidden_field :beer_club_id %>
    <%= f.submit value:"join the club", class:'btn btn-primary' %>
  <% end %>
<%end%>

<% if current_user && !@beer_club.user_not_member?(current_user) && @beer_club.memberships.find_by_user_id(current_user.id).confirmed == true %>

<% if current_user && !@beer_club.user_not_member?(current_user) %>
  <%= form_for(@membership, method: "delete") do |f| %>
    <%= f.hidden_field :beer_club_id %>
    <%= f.submit value: "end the membership", class:'btn btn-danger' %>
  <% end %>
<% end %>


<%= edit_and_destroy_buttons(@beer_club) %>
<% end%>