config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'breweries#index'
  get 'kaikki_bisset', to: 'beers#index'
  resources :ratings, only: [:index, :new, :create, :destroy]
  get 'signup', to: 'users#new'
  resource :session, only: [:new, :create, :destroy]
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  resources :memberships, only: [:index,:new, :create, :destroy]
  resources :places, only: [:index, :show]
  get 'places', to: 'places#index'
  post 'places', to:'places#search'
  get 'styles', to: 'styles#index'
  resources :styles, only: [:index, :show, :create, :destroy, :edit]
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :users do
    post 'toggle_activity', on: :member
  end
  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'
  get 'auth/:provider/callback', to: 'sessions#create_oauth'
  resources :memberships do
    post 'toggle_confirmed', on: :member
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ratebeer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'breweries', breweries_path, { class: "nav-link" } %>
          </li>      
          <li class="nav-item">
            <%= link_to 'beers', beers_path, { class: "nav-link" } %>
          </li>     
          <li class="nav-item">
            <%= link_to 'styles', styles_path, { class: "nav-link" } %>
          </li>   
          <li class="nav-item">
            <%= link_to 'ratings', ratings_path, { class: "nav-link" } %>
          </li>       
          <li class="nav-item">
            <%= link_to 'users', users_path, { class: "nav-link" } %>
          </li>  
          <li class="nav-item">
            <%= link_to 'clubs', beer_clubs_path, { class: "nav-link" } %>
          </li>   
          <li class="nav-item">
            <%= link_to 'places', places_path, { class: "nav-link" } %>
          </li> 
          <% if current_user %>
            <div class="nav-item dropdown">
              <li data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= link_to current_user.username, current_user, { class:"nav-link dropdown-toggle" } %>
              </li> 
              <ul class="dropdown-menu">
                <li> <%= link_to "my page", current_user, { class: "dropdown-item" } %> </li>
                <li> <%= link_to 'rate a beer ', new_rating_path, { class: "dropdown-item" } %> </li>
                <li><%= link_to 'join a club ', new_membership_path, { class: "dropdown-item"} %></li>
                <li>  <%= link_to 'signout', signout_path, { class: "dropdown-item", method: :delete  } %>   </li> 
              </ul> 
            </div>               
          <% else %>
            <li class="nav-item">
              <%= link_to 'signin', signin_path, { class: "nav-link" } %>
            </li>  
            <li class="nav-item">
              <%= link_to 'signin with GitHub','auth/github', {class: "nav-link"} %>
              </li>
            <li class="nav-item">
              <%= link_to 'signup', signup_path, { class: "nav-link" } %>
            </li>                        
          <% end %>                            
        </ul>
      </div>
    </nav>

    <div class="container">
    <% if notice %>
    <div class="alert alert-primary" role="alert">
      <%= notice %>
    </div>
  <% end %>
  <div class="row">
    <div class="col-sm-8">
      <%= yield %>
    </div>
    <div class="col-sm-4">
      <img 
        src="http://www.cs.helsinki.fi/u/mluukkai/wadror/pint.jpg" 
        width="200"
        style="padding-top:30px"
      >
    </div>
  </div>
</div>
  </body>
</html>